# Generated by Django 4.2.3 on 2023-07-26 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_schedule_alter_course_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='staus',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='course',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 12, 20, 59, 746549)),
        ),
    ]
